lib/clerk/authenticatable.rb
lib/clerk/rack_middleware.rb
lib/clerk/railtie.rb

The proxy object is what [Warden](https://github.com/wardencommunity/warden/blob/master/lib/warden/proxy.rb) also uses. This way, we never run anything until the last moment it's needed.

Lazy load Clerk session and user

---

lib/clerk/resources/users.rb
test/fixtures/users_oauth_access_token.json
test/resources/users_test.rb

See https://docs.clerk.dev/backend/backend-api-reference/beta-features#retrieve-an-oauth-access-token-for-a-user

feat: Add /users OAuth access token method

---

lib/clerk/rack_middleware_v2.rb

If the request looks like it came from a non-browser (e.g. curl), we
avoid rendering the interstitial since we know it can't work there - the
interstitial relies on the browser rendering the HTML response. In such
cases, the request is considered unauthenticated.
We only do this for development and staging instances for now. In the
future we might enable it for production too, if it proves a robust
mechanism.

fix: Skip interstitial on non-browser requests

---

README.md
lib/clerk.rb
lib/clerk/rack_middleware_v2.rb

This patch adds a new configuration option, with which one is able to declare routes that the middleware should not execute on.
This is done by either specifying an exact match, e.g. "/foo" or a prefix match, e.g. "/foo/*".
The latter syntax is implemented using a naive linear search, but since most people will use only a handful of those entries, this should be fine. (If we want to optimize this later on, we could use a prefix tree or something similar.)

feat: Add support for excluding routes in middleware

---

lib/clerk/authenticatable.rb
lib/clerk/rack_middleware_v2.rb

This fetches the organization ID of the currently authenticated session, if any. Otherwise it returns nil.

feat: Add clerk_organization & clerk_organization_id helpers

---

lib/clerk/rack_middleware_v2.rb

Upcoming secret keys will start with `sk_` prefix, so adding support for that format in `development_or_staging?` as well.

feat: Support new secret key format in development_or_staging? check

---

Gemfile.lock
clerk-sdk-ruby.gemspec
lib/clerk/jwks_cache.rb
lib/clerk/sdk.rb
test/sdk_test.rb

After 1123911 the JWKs cache wasn't working as expected, since the
middleware constructed a new SDK instance on each request. So each
request was effectively bypassing the cache, since the cache was
essentially an instance variable which was re-initialized anew every
time.
With this change, the JWKs cache is made thread-safe and shared between
all instances of the SDK.
Fixes AUTH-76

fix: Make JWKS cache shared between SDK instances

---

lib/clerk.rb

If this env var is set, it will take precedence over CLERK_API_KEY.
Part of AUTH-75

feat: Read Backend API key from CLERK_SECRET_KEY

---

.gitignore
Gemfile.lock
lib/clerk/resources/singular_resource.rb
lib/clerk/sdk.rb
test/sdk_test.rb

The Backend API supports both form-urlencoded and application/json content types in requests. However, we're slowly fading out support for form-urlencoded and transitioning to application/json.
Most important, the Ruby SDK generated payloads that the Backend API couldn't properly unmarshal, particularly in the case of payloads like the following:
{ backup_codes: ["abcdef", "zxcqwe"] }
in such cases, the resulting payload would be:
backup_codes[]: "abcdef; zxcqwe"
which the Backend API didn't know how to properly parse.
Fixes AUTH-129

fix: Use JSON Content-Type in mutating requests

---

CODEOWNERS
Gemfile.lock
lib/clerk/rack_middleware_v2.rb

Set signed-out as default request state and return interstitial ONLY when the token verification fails with expired or invalid issued_at (iat) errors.
Extra actions:
**REVIEW IT PER COMMIT**

fix: interstitial of failed token verification

---

CHANGELOG.md
README.md
lib/clerk/authenticatable.rb

Replace all occurrences of `clerk.dev` with `clerk.com` in the repo docs

chore: Migrate README urls to clerk.com

---

Gemfile.lock
clerk-sdk-ruby.gemspec
lib/clerk/sdk.rb

chore: Allow use of Faraday v2

---

Gemfile.lock
lib/clerk/rack_middleware_v2.rb
lib/clerk/sdk.rb

This fixes a regression introduced with #37, which caused the Clerk API key to not be properly set when requesting Clerk's Backend API, when Faraday v2 was used.
Fixes https://github.com/clerkinc/clerk-sdk-ruby/pull/37#issuecomment-1786060568

fix: Properly set API key in Faraday 2

---

README.md
lib/clerk.rb
lib/clerk/authenticate_context.rb
lib/clerk/authenticate_request.rb
lib/clerk/constants.rb
lib/clerk/rack_middleware.rb
lib/clerk/rack_middleware_v2.rb
lib/clerk/sdk.rb

- Drop `Clerk::SDK#interstitial` method (it should not be used by any customer since this is internal)
- Replace the interstitial mechanism with the handshake mechanism
- Extract logic from the RackMiddlewareV2 to `AuthenticateRequest` class
- Extract data used from the request and the configuration to `AuthenticateContext` class ([Parameter object pattern](https://refactoring.guru/introduce-parameter-object))
- Introduce constants module to centralize and re-use the constants value used across the SDK
- Interstitial HTML page rendered when we cannot determine the request state is replaced with 2 HTTP 307 redirects
- Introduced `CLERK_PUBLISHABLE_KEY` env which is required for the handshake to work properly
- `CLERK_SECRET_KEY` should use the format `sk_test | sk_live` format
- Add tests …

feat(backend): Introduce handshake & extract logic auth logic to separate classes

---

.github/workflows/semgrep.yml

Add semgrep in monitoring mode to scan for security issues in the background such as:
- Committed secrets
- First-party code vulnerabilities
- Dependency vulnerabilities

chore: add github action for semgrep to run security scans in monitoring mode

---

CHANGELOG.md
Gemfile.lock
README.md
lib/clerk/version.rb

Generating new beta release since i yanked the `4.0.0.beta1` because the gem was published from a branch

Prepare for 4.0.0.beta2 release

---

Gemfile.lock
lib/clerk/rack_middleware_v2.rb
lib/clerk/version.rb

Handle 2 interstitial cases:
- when there is `client_uat` and `cookie token` info (both for dev and production apps)
- when `client_uat` has a value that does not match with the `cookie token` value
- client_uat = 0 (signed-out) but cookie token has value (signed-in)
- client_uat does NOT have value (??) but cookie token has value (signed-in)
- client_uat = 123... (signed-in) but cookie token does NOT havue value (signed-out)

fix: Incompatible __client_uat & __session should show interstitial

---

CHANGELOG.md
lib/clerk/rack_middleware_v2.rb
lib/clerk/version.rb

- Bumps the version to v3.1.0
- Applies fix to v3.1.0.rc.1 which lead to infinite redirect loop (introduced in v3.1.0.rc.1)

fix: Release version 3.1.0 with production instance hotfixes

---

CHANGELOG.md
Gemfile.lock
lib/clerk/version.rb

- fix: Make publishable_key and secret_key required without making the envs required [https://github.com/clerk/clerk-sdk-ruby/pull/53]

Prepare for 4.0.0.beta3 release

---

Gemfile.lock
lib/clerk/rack_middleware_v2.rb
lib/clerk/version.rb

This change fixes an infinite redirect issue when a user is signed-out but the `__session` cookie still exists with value.
The above scenario can be reproduced by using sign-out from Account Portal and then refresh a page of the app.

fix: Always return signed-out when client_uat=0

---

lib/clerk/authenticatable.rb
lib/clerk/proxy.rb

Breaking changes:
- Rename `clerk_verified_session_claims` to `clerk_session_claims`
- Drop `clerk_verified_session_token`
- Drop `clerk_session`
- Drop `clerk_reverify_session!` - not implemented
Changes:
- Drop unused fetch of session resource in ProxyV2

fix: Cleanup and fix Authenticatable concern exposed helpers

---

lib/clerk/authenticate_request.rb

Fixes https://github.com/clerk/clerk-sdk-ruby/issues/61

fix: Error caused by comparing auth_context.client_uat as string

---

lib/clerk.rb
lib/clerk/authenticatable.rb
lib/clerk/constants.rb
lib/clerk/rack_middleware_v2.rb

feat: Add helpers for reverification

---

CODEOWNERS

More teams will have their hands in this repo. As such, it makes sense to remove the strict requirement of the backend team as required reviewers.
Similarly to `clerk/javascript`, I opted to remove it entirely to reduce unnecessary noise.

repo: Expand scope of reviewers

---

.github/workflows/main.yml
Gemfile.lock
clerk-sdk-ruby.gemspec
lib/clerk/jwks_cache.rb
lib/clerk/proxy.rb
lib/clerk/sdk.rb
lib/clerk/utils.rb
lib/clerk/version.rb
spec/clerk/jwks_cache_spec.rb
spec/clerk/proxy_spec.rb
spec/clerk/sdk_spec.rb

- Removes the need for `.respond_to_missing?` / `.method_missing` thanks to improved generation flows in the OpenAPI Java generators.
- More-closely maps the OAS versus creating our own method names to reduce overall long-term maintainance.

feat: Updates relative to clerk-http-client@2.0.0.beta5

---

Gemfile.lock
README.md
apps/rails-api/Gemfile.lock
apps/rails-full/Gemfile.lock
bin/release
lib/clerk/rails.rb
lib/clerk/railtie.rb
lib/clerk/version.rb
spec/clerk/sdk_spec.rb

Clerk SDK Ruby 4.0.0.beta6
- Allows for users to be able to skip the automatic addition of the Clerk Middleware via Railties.
- Introduces a repeatable release flow.
Fixes ECO-336
Closes #80

feat: Skippable Railties & Release Flow

---

lib/clerk/rack_middleware.rb
lib/clerk/utils.rb

`parse_cookies_header` isn't available on older versions of Rack. Replicate in `Clerk::Utils`
Closes #91

feat: Enable older versions of Rack

---

CHANGELOG.md
lib/clerk/authenticate_request.rb
lib/clerk/constants.rb
lib/clerk/proxy.rb
lib/clerk/version.rb
spec/clerk/authenticate_request_spec.rb
spec/clerk/proxy_spec.rb
spec/clerk/rack_middleware_spec.rb

`Rack::Lint` fails if included elsewhere in the middleware stack.

fix: Only return lowercase headers (Rack::Lint)
